In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [47]:
dataset = pd.read_csv("used_cars_data.csv")

In [49]:
dataset

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN,NaN

In [51]:
dataset.isnull().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 46
Power                  46
Seats                  53
New_Price            6247
Price                1234
dtype: int64

In [53]:
#now drop columns with large missing valeu s
dataset = dataset.dropna(subset = ['Price'])
dataset.shape

(6019, 14)

In [55]:
dataset = dataset.drop(columns = ['S.No.', 'New_Price'])

In [57]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6019 entries, 0 to 6018
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               6019 non-null   object
 1   Location           6019 non-null   object
 2   Year               6019 non-null   int64
 3   Kilometers_Driven  6019 non-null   int64
 4   Fuel_Type          6019 non-null   object
 5   Transmission       6019 non-null   object
 6   Owner_Type         6019 non-null   object
 7   Mileage            6017 non-null   object
 8   Engine             5983 non-null   object
 9   Power              5983 non-null   object
 10  Seats              5977 non-null   float64
 11  Price              6019 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 611.3+ KB

In [59]:
dataset['Car_age'] = 2026 - dataset['Year']
dataset['Brand'] = dataset['Name'].str.split().str[0]

In [65]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6019 entries, 0 to 6018
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               6019 non-null   object
 1   Location           6019 non-null   object
 2   Year               6019 non-null   int64
 3   Kilometers_Driven  6019 non-null   int64
 4   Fuel_Type          6019 non-null   object
 5   Transmission       6019 non-null   object
 6   Owner_Type         6019 non-null   object
 7   Mileage            6017 non-null   object
 8   Engine             5983 non-null   object
 9   Power              5983 non-null   object
 10  Seats              5977 non-null   float64
 11  Price              6019 non-null   float64
 12  Car_age            6019 non-null   int64
 13  Brand              6019 non-null   object
dtypes: float64(2), int64(3), object(9)
memory usage: 705.4+ KB

In [71]:
dataset = dataset.drop(columns = ['Year', 'Name'])

In [73]:
dataset.head()

,Location,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Car_age,Brand
0,Mumbai,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,1.75,16,Maruti
1,Pune,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,12.50,11,Hyundai
2,Chennai,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,4.50,15,Honda
3,Chennai,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,6.00,14,Maruti
4,Coimbatore,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,17.74,13,Audi

In [79]:
#num extract from string 
dataset['Mileage'] = dataset['Mileage'].str.extract(r'([\d.]+)').astype(float)
dataset['Engine'] = dataset['Engine'].str.extract(r'([\d.]+)').astype(float)
dataset['Power'] = dataset['Power'].str.extract(r'([\d.]+)').astype(float)

In [81]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6019 entries, 0 to 6018
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Location           6019 non-null   object
 1   Kilometers_Driven  6019 non-null   int64
 2   Fuel_Type          6019 non-null   object
 3   Transmission       6019 non-null   object
 4   Owner_Type         6019 non-null   object
 5   Mileage            6017 non-null   float64
 6   Engine             5983 non-null   float64
 7   Power              5876 non-null   float64
 8   Seats              5977 non-null   float64
 9   Price              6019 non-null   float64
 10  Car_age            6019 non-null   int64
 11  Brand              6019 non-null   object
dtypes: float64(5), int64(2), object(5)
memory usage: 611.3+ KB

In [83]:
dataset.head()

,Location,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Car_age,Brand
0,Mumbai,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75,16,Maruti
1,Pune,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,11,Hyundai
2,Chennai,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4.50,15,Honda
3,Chennai,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00,14,Maruti
4,Coimbatore,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74,13,Audi

In [85]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(dataset, test_size = 0.2, random_state = 42)

In [87]:
print('Train', train_set.shape)
print("Test", test_set.shape)

Train (4815, 12)
Test (1204, 12)

In [93]:
car_data = train_set.copy()

In [95]:
car_data.head()

,Location,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Car_age,Brand
4248,Delhi,76155,Petrol,Manual,First,18.60,1199.0,79.40,5.0,1.95,15,Chevrolet
4129,Coimbatore,64637,Diesel,Manual,First,22.77,1498.0,98.59,5.0,7.52,12,Ford
2534,Kolkata,2900,Diesel,Manual,First,24.30,1248.0,88.50,5.0,8.75,8,Maruti
2893,Delhi,150000,Diesel,Manual,First,12.99,2494.0,100.60,8.0,6.95,15,Toyota
2860,Hyderabad,98500,Diesel,Manual,First,22.95,1248.0,74.00,5.0,6.00,9,Tata

In [97]:
corr_matrix = train.corr(numeric_only = True)
corr_matrix['Price'].sort_values()

Mileage             -0.306593
Car_age             -0.305327
Kilometers_Driven   -0.011493
Seats                0.052225
Engine               0.658354
Power                0.772566
Price                1.000000
Name: Price, dtype: float64

In [107]:
#now set the y 
X_train = car_data.drop('Price', axis = 1)
y_train = car_data['Price'].copy()

In [109]:
X_test = test_set.drop('Price', axis = 1)
y_test = test_set['Price'].copy

In [121]:
y_train.shape

(4815,)

In [147]:
#now claassifiy num and columns 
num_cols = X_train.select_dtypes(include = ['int64', 'float64']).columns.tolist()
cat_cols = X_train.select_dtypes(include = ['object']).columns.tolist()
#this return list of columns not there name

In [149]:
print('num_cols', num_cols)
print('cat_cols', cat_cols)

num_cols ['Kilometers_Driven', 'Mileage', 'Engine', 'Power', 'Seats', 'Car_age']
cat_cols ['Location', 'Fuel_Type', 'Transmission', 'Owner_Type', 'Brand']

In [151]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

num_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy = 'median')),
    ('scaler', StandardScaler()),
])

cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy = 'most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown = 'ignore', sparse_output = False)),
])

full_pipeline = ColumnTransformer([
    ('num', num_pipeline, num_cols),
    ('cat', cat_pipeline, cat_cols)
])

In [153]:
print(type(num_cols))
print(type(cat_cols))

print(num_cols)
print(cat_cols)

<class 'list'>
<class 'list'>
['Kilometers_Driven', 'Mileage', 'Engine', 'Power', 'Seats', 'Car_age']
['Location', 'Fuel_Type', 'Transmission', 'Owner_Type', 'Brand']

In [155]:
#fit_transform on training data only
# pipeline learns medains, mode, encoder categories from training set onl
X_train_prepared = full_pipeline.fit_transform(X_train)

#for test set only transform then not fit
X_test_prepared = full_pipeline.transform(X_test)

In [169]:
X_train_prepared.shape

(4815, 57)

<h3>Select Nd train data</h3>

In [182]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(X_train_prepared, y_train)

LinearRegression()

In [200]:
lin_reg.predict()

Price
2.42      1
4.02      1
19.97     1
45.64     1
90.00     1
         ..
3.25     59
3.50     62
5.50     64
4.25     65
4.50     71
Name: count, Length: 1223, dtype: int64